-- SpaceGen AI — Production PostgreSQL Schema
-- Section 25: Projects, Captures, Scenes, Objects, Variants, Edits, and AI Jobs

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- 1. Users / Accounts
CREATE TABLE IF NOT EXISTS users (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    email VARCHAR(255) UNIQUE NOT NULL,
    full_name VARCHAR(255),
    plan_tier VARCHAR(50) DEFAULT 'free', -- free, pro, studio, enterprise
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- 2. Projects
CREATE TABLE IF NOT EXISTS projects (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    user_id UUID REFERENCES users(id) ON DELETE CASCADE,
    name VARCHAR(255) NOT NULL,
    description TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- 3. Captures (raw uploaded video sessions)
CREATE TABLE IF NOT EXISTS captures (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    project_id UUID REFERENCES projects(id) ON DELETE CASCADE,
    video_url TEXT NOT NULL,
    video_duration_sec REAL,
    video_resolution VARCHAR(50),
    file_size_bytes BIGINT,
    status VARCHAR(50) DEFAULT 'uploaded', -- uploaded, processing, completed, failed
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- 4. Reconstruction Jobs & AI Worker Tasks
CREATE TABLE IF NOT EXISTS ai_jobs (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    job_id VARCHAR(64) UNIQUE NOT NULL,
    capture_id UUID REFERENCES captures(id) ON DELETE SET NULL,
    project_id UUID REFERENCES projects(id) ON DELETE CASCADE,
    job_type VARCHAR(50) NOT NULL, -- reconstruction, segmentation, hero_render, variant_gen
    status VARCHAR(50) NOT NULL DEFAULT 'queued', -- queued, running, completed, failed
    progress INTEGER DEFAULT 0,
    current_step VARCHAR(255),
    logs TEXT,
    result_data JSONB,
    error_message TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- 5. Digital Twin Scenes (Reconstructed Spaces)
CREATE TABLE IF NOT EXISTS scenes (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    project_id UUID REFERENCES projects(id) ON DELETE CASCADE,
    capture_id UUID REFERENCES captures(id) ON DELETE SET NULL,
    name VARCHAR(255) NOT NULL,
    room_type VARCHAR(100) DEFAULT 'Living Room',
    style VARCHAR(100) DEFAULT 'Modern',
    splat_model_url TEXT,
    splat_format VARCHAR(20) DEFAULT 'ply', -- ply, spz, ksplat
    splat_point_count BIGINT,
    hero_image_url TEXT,
    dimensions JSONB, -- { width_m, height_m, depth_m }
    lighting JSONB,   -- { natural_light_direction, light_sources: [...] }
    camera_poses JSONB, -- Registered camera viewpoints from COLMAP
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- 6. Scene Objects (Semantic graph entities: furniture, architecture, lighting)
CREATE TABLE IF NOT EXISTS scene_objects (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    scene_id UUID REFERENCES scenes(id) ON DELETE CASCADE,
    entity_id VARCHAR(64) NOT NULL, -- e.g. "sofa_01", "wall_north"
    type VARCHAR(50) NOT NULL,      -- architecture, furniture, lighting, decor
    category VARCHAR(100) NOT NULL,  -- sofa, table, wall, floor, lamp
    subcategory VARCHAR(100),
    name VARCHAR(255),
    position JSONB,                 -- { x, y, z }
    dimensions JSONB,               -- { width_m, depth_m, height_m }
    material JSONB,                 -- { type, color, finish, texture }
    style VARCHAR(100),
    confidence REAL DEFAULT 0.95,
    editable BOOLEAN DEFAULT TRUE,
    is_visible BOOLEAN DEFAULT TRUE,
    replaced_by_asset_url TEXT,     -- 3D GLB model URL if swapped
    bounding_box JSONB,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(scene_id, entity_id)
);

-- 7. Spatial Relationships (Scene graph edges)
CREATE TABLE IF NOT EXISTS spatial_relationships (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    scene_id UUID REFERENCES scenes(id) ON DELETE CASCADE,
    subject_entity_id VARCHAR(64) NOT NULL,
    relation VARCHAR(50) NOT NULL, -- facing, next_to, on_top_of, against, contains
    object_entity_id VARCHAR(64) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- 8. Design Variants (Alternative concepts generated by Gemini)
CREATE TABLE IF NOT EXISTS design_variants (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    scene_id UUID REFERENCES scenes(id) ON DELETE CASCADE,
    style_name VARCHAR(100) NOT NULL,
    description TEXT,
    hero_image_url TEXT NOT NULL,
    parameters JSONB,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- 9. Scene Edits History (Multi-turn conversational edits)
CREATE TABLE IF NOT EXISTS scene_edits (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    scene_id UUID REFERENCES scenes(id) ON DELETE CASCADE,
    user_prompt TEXT NOT NULL,
    ai_response TEXT,
    action_plan JSONB,
    resulting_image_url TEXT,
    modified_objects JSONB,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Indexes for ultra-fast query performance
CREATE INDEX IF NOT EXISTS idx_scenes_project_id ON scenes(project_id);
CREATE INDEX IF NOT EXISTS idx_scene_objects_scene_id ON scene_objects(scene_id);
CREATE INDEX IF NOT EXISTS idx_ai_jobs_job_id ON ai_jobs(job_id);
CREATE INDEX IF NOT EXISTS idx_ai_jobs_status ON ai_jobs(status);
